spring:
   application:
      name: zuul-server
server:
   port: 8762
zuul:
   routes:
      foos:
         path: /estacionamiento/**
         url: http://localhost:8085/estacionamiento
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
   instance:
      preferIpAddress: true